exports.chats =[
    {
        isGroupChat:false,
        users:[
            {
                name:"jhone",
                email:"jhone@gmail.com"
            },{
                name:"ram",
                email:"ram@gmail.com"
            }
        ],
        _id:"617a007dkok312we",
        chatName:"jhone"
    },
    {
        isGroupChat:false,
        users:[
            {
                name:"ram",
                email:"ram@gmail.com"
            },{
                name:"ram",
                email:"ram@gmail.com"
            }
        ],
        _id:"617a007dkok312we",
        chatName:"ram"
    },
    {
        isGroupChat:false,
        users:[
            {
                name:"bot",
                email:"bot@gmail.com"
            },{
                name:"bot",
                email:"bot@gmail.com"
            }
        ],
        _id:"617a007dkok312we",
        chatName:"bot"
    },
    {
        isGroupChat:false,
        users:[
            {
                name:"ozil",
                email:"ozil@gmail.com"
            },{
                name:"ozil",
                email:"ozil@gmail.com"
            }
        ],
        _id:"617a007dkok312we",
        chatName:"ozil"
    },
    {
        isGroupChat:false,
        users:[
            {
                name:"messi",
                email:"messi@gmail.com"
            },{
                name:"messi",
                email:"messi@gmail.com"
            }
        ],
        _id:"617a007dkok312we",
        chatName:"messi"
    },
    {
        isGroupChat:false,
        users:[
            {
                name:"savy",
                email:"savy@gmail.com"
            },{
                name:"savy",
                email:"savy@gmail.com"
            }
        ],
        _id:"617a007dkok312we",
        chatName:"savy"
    },
    {
        isGroupChat:false,
        users:[
            {
                name:"rony",
                email:"rony@gmail.com"
            },{
                name:"rony",
                email:"rony@gmail.com"
            }
        ],
        _id:"617a007dkok312we",
        chatName:"rony"
    }

]